main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,7 +15,7 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Setup .NET
-        uses: actions/setup-dotnet@v6
+        uses: actions/setup-dotnet@v3  # Use the appropriate version, like 'v2', 'v3', etc.
         with:
           dotnet-version: '6.0.x'
 
@@ -28,6 +28,15 @@ jobs:
       - name: Publish
         run: |
           dotnet publish ./MakePipeline.sln --configuration Release --no-build --output /tmp/publish
+          if [ $? -ne 0 ]; then
+            echo "Error: dotnet publish command failed."
+            exit 1
+          fi
+          publish_dir=$(realpath /tmp/publish)
+          echo "##vso[task.setvariable variable=PUBLISH_DIR;isOutput=true]$publish_dir"
+
+      - name: Display Publish Directory
+        run: echo "Publish Directory: ${{ env.PUBLISH_DIR }}"
 
       - name: Deploy to SmarterASP.NET
         uses: SamKirkland/FTP-Deploy-Action@3.1.1
