Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,7 +25,15 @@ jobs:
         run: dotnet build ./MakePipline.sln --configuration Release --no-restore
 
       - name: Publish
-        run: dotnet publish ./MakePipline.sln --configuration Release --no-build
+        run: |
+          dotnet publish ./MakePipeline.sln --configuration Release --no-build --output /tmp/publish
+          if [ $? -ne 0 ]; then
+            echo "Error: dotnet publish command failed."
+            exit 1
+          fi
+          publish_dir=$(realpath /tmp/publish)
+          echo "##vso[task.setvariable variable=PUBLISH_DIR;isOutput=true]$publish_dir"
+      
 
         
       - name: Deploy to SmarterASP.NET
@@ -35,3 +43,4 @@ jobs:
           username: 'makepiplin-001'
           password: 'Aa@12345'
           server-dir: '/www/makepipline/'  # Replace with your target directory on the server
+          local-dir: ${{ env.PUBLISH_DIR }} # Replace with the path to your published artifacts
